<?php
 /**
 * Implements hook_field_schema()
 */
    function dynamic_unit_field_schema($field) {
       return array(
         'columns' => array(
			 'std_value' => array(
				'type' => 'numeric',
			    'precision' => '10',
			    'scale' => '2',
				'not null' => TRUE,
				'default'  => 0 
				),
			'label_id' => array(
				'type' => 'varchar',
				'not null' => TRUE,
				'default'  => ''
				),
            ),
         ),
     );
   }